### ISSUE TITLE
exist status: 256 run on cnvnator stage

### ISSUE THREAD

**Issue by OlenaMaiakovska** [KCCG/ClinSV#41]
Hi all,

I am running test dataset based on refdata-b38 and got the following error:
"error exist status != 0 (256), please check /app/project_folder/SVs/FR05812606/cnvnator/sh/cnvnator.caller.FR05812606.e for more information".

The error file last lines comprise message:  
"
===== Running calls on input data
Traceback (most recent call last):
  File "/app/clinsv/cnvnator-multi/cnvnator_wrapper.py", line 234, in <module>
    mk_graph_file(args.output)
  File "/app/clinsv/cnvnator-multi/cnvnator_wrapper.py", line 182, in mk_graph_file
    start = int(pieces[1][idx+1:idx2])
ValueError: invalid literal for int() with base 10: 'o'
"
Can anybody help to figure out the reason? 
Thank you!

**Comment by drmjc** [comment]
thanks for reporting this Olena, this is a new one for us. What command did you run please?
